[package]
name = "libgit2-demo"
version = "0.1.0"
authors = ["荒野無燈 <ttys3@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = { version = "0.13.17", default-features = false, features = [] }
